//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordGuessApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomWordsDatabase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomWordsDatabase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordGuessApplication.CustomWordsDatabase", typeof(CustomWordsDatabase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aardvark
        ///aardwolf
        ///aaron
        ///aback
        ///abacus
        ///abaft
        ///abalone
        ///abandon
        ///abandoned
        ///abandonment
        ///abandons
        ///abase
        ///abased
        ///abasement
        ///abash
        ///abashed
        ///abate
        ///abated
        ///abatement
        ///abates
        ///abattoir
        ///abattoirs
        ///abbe
        ///abbess
        ///abbey
        ///abbeys
        ///abbot
        ///abbots
        ///abbreviate
        ///abbreviated
        ///abbreviates
        ///abbreviating
        ///abbreviation
        ///abbreviations
        ///abdicate
        ///abdicated
        ///abdicates
        ///abdicating
        ///abdication
        ///abdomen
        ///abdomens
        ///abdominal
        ///abduct
        ///abducted
        ///abducting
        ///abduction
        ///abductions
        ///abductor
        ///abductors
        ///abducts
        ///abe
        ///abeam
        ///abel
        ///abe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to able
        ///aced
        ///aces
        ///ache
        ///acid
        ///acne
        ///acre
        ///acts
        ///adds
        ///afar
        ///afro
        ///aged
        ///ages
        ///ahoy
        ///aide
        ///aids
        ///ails
        ///aims
        ///aint
        ///airs
        ///akin
        ///alas
        ///ally
        ///also
        ///amen
        ///amid
        ///ammo
        ///amok
        ///anal
        ///anew
        ///anti
        ///ants
        ///anus
        ///apes
        ///aqua
        ///arab
        ///arch
        ///arcs
        ///area
        ///arks
        ///arms
        ///army
        ///arts
        ///asia
        ///asks
        ///atom
        ///aunt
        ///aura
        ///auto
        ///avid
        ///away
        ///axes
        ///axis
        ///axle
        ///babe
        ///baby
        ///back
        ///bags
        ///bail
        ///bait
        ///bake
        ///bald
        ///bale
        ///ball
        ///band
        ///bane
        ///bang
        ///bank
        ///bans
        ///barb
        ///bard
        ///bare
        ///bark
        ///barn
        ///bars
        ///bart
        ///base
        ///bash
        ///bask
        ///bass
        ///bate
        ///bath
        ///bats
        ///baud
        ///bawl
        ///bays
        ///bead
        ///beak
        ///beam
        ///bean
        ///bear
        ///beat
        ///beau
        ///beck
        ///beds
        ///beef
        ///been
        ///beep
        ///beer
        ///bees
        ///beet
        ///begs
        ///be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordsSorted {
            get {
                return ResourceManager.GetString("wordsSorted", resourceCulture);
            }
        }
    }
}
